apiVersion: v1
kind: Pod
metadata:
  name: pod-cert
spec:
  containers:
    - name: pod-cert
      image: nginx
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: sql-creds
            key: username
      - name: PASSWORD
        valueFrom:
        secretKeyRef:
          name: sql-creds
