apiVersion: v1
kind: Pod
metadata:
  name: pod-cert
spec:
  containers:
    - name: pod-cert
      image: nginx
      env:
      - name: SQL_USER
        valueFrom:
          secreetKeyRef:
            name: sql-creds
            key: username
      - name: SQL_pass
        valueFrom:
        secreetKeyRef:
          name: sql-creds
